### PR TITLE
Add annotations to Sample API

### PR DESCRIPTION
**Pull request by dongbohu**
@vincerubinetti: Here is a demo page with sample annotations in `Sampe` API:
https://py3-adage.greenelab.com/api/v1/sample/

If it looks okay with you, please approve it and I will have it deployed. Thanks.

### CODE REVIEW

**Review by vincerubinetti — APPROVED** [review]

**Comment by vincerubinetti** [comment]
@dongbohu I didn't catch this, but I think we want to keep the `experiments` field in the response here too, so I can link to the related experiments of a specific sample. I believe that would just involve changing `fields = ('id', 'name', 'ml_data_source', 'experiments', 'annotations')`. Can you make another PR?

**Comment by dongbohu** [comment]
@vincerubinetti: No, it's not that simple, because `experiements` in `Sample` model is a many-to-many relationship field, not a regular field. How about having an `experiments` field that includes a list of only the related experiments' primary keys (`accession`)?

**Comment by vincerubinetti** [comment]
Just the ids (`accession`) is fine, like it was returning before.

**Comment by dongbohu** [comment]
Done. It is already deployed.

**Pull request merged**
